# How to create 9 random probs and make their sum to 1.0

In [1]:
import numpy as np
import random

In [2]:
rand_probs = np.random.rand(1,9)

rand_probs    # 9 random prob (0-1)

array([[0.36471361, 0.74146448, 0.46719268, 0.23565416, 0.52895203,
        0.72367919, 0.57238266, 0.67075529, 0.42591645]])

In [5]:
# take sum of it 

sum(rand_probs)

array([0.36471361, 0.74146448, 0.46719268, 0.23565416, 0.52895203,
       0.72367919, 0.57238266, 0.67075529, 0.42591645])

In [18]:
sum_of_rand_prob = sum(sum(rand_probs))

In [21]:
sum_of_rand_prob 

4.730710554020636

In [19]:
# div by rand_probs to make it 1
sum_to_1 = rand_probs/sum_of_rand_prob

In [20]:
sum_to_1

array([[0.07709489, 0.15673427, 0.0987574 , 0.04981369, 0.11181239,
        0.15297473, 0.12099296, 0.14178743, 0.09003224]])

In [16]:
sum(sum(sum_to_1))

1.0

# For 10 rows with 9 classes

In [24]:
for i in range(11):
    rand_probs = np.random.rand(1,9)
    print(rand_probs)  

[[0.88873383 0.2787044  0.80332433 0.27741153 0.02952431 0.30833106
  0.69139427 0.83826956 0.66791798]]
[[0.41483666 0.68358536 0.39455867 0.88285765 0.60833868 0.62499099
  0.55525902 0.61194044 0.7719719 ]]
[[0.03521602 0.52596439 0.573757   0.51565535 0.80266438 0.37143534
  0.92209314 0.87517472 0.38111368]]
[[0.28949698 0.42015038 0.82461722 0.57125101 0.03450564 0.06521506
  0.04877809 0.58913568 0.17033774]]
[[0.20279654 0.84568312 0.94812984 0.94675263 0.68074264 0.44812174
  0.37826832 0.16081797 0.06844811]]
[[0.38622082 0.69436778 0.84693014 0.48249284 0.75021063 0.69017207
  0.39687539 0.02977612 0.23321414]]
[[0.35092377 0.34699152 0.05953659 0.47511627 0.02670287 0.08538136
  0.09520415 0.86752811 0.20527771]]
[[0.89445932 0.61636528 0.51563249 0.0206109  0.71447938 0.86977709
  0.97210823 0.28020506 0.71404561]]
[[0.16331974 0.44934442 0.13332362 0.66456504 0.50318826 0.96811017
  0.62024635 0.67100899 0.78629735]]
[[0.83466687 0.16675826 0.33367897 0.57381487 0.2381306

#### Observation: we got here 10 data points with random_probs

In [25]:
sum(rand_probs)    # This will sum up all the rows

array([0.5221207 , 0.97725155, 0.97334474, 0.35812356, 0.63362699,
       0.25022044, 0.87557457, 0.78710712, 0.23786938])

In [26]:
sum(sum(rand_probs))  # this will sum up all the col too

5.615239062732656

In [27]:
sum_all_random_probs = sum(sum(rand_probs))

In [31]:
# Now divide with random prob to sum it to 1

div = rand_probs/sum_all_random_probs

div

array([[0.09298281, 0.17403561, 0.17333986, 0.06377708, 0.11284061,
        0.04456096, 0.15592828, 0.1401734 , 0.0423614 ]])

In [35]:
sum(sum(div))   # done

1.0